print("Welcome to The Tic Tac Toe Game")
print("##########    ##########   ########## ")
print("   ###            ###          ###")
print("   ###            ###          ###")
print("   ###            ###          ###")
print("   ###            ###          ###")
print("   ###            ###          ###")
print("   ###            ###          ###")
